import{a as w,S as L,i as h}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function c(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerpolicy&&(t.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?t.credentials="include":o.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(o){if(o.ep)return;o.ep=!0;const t=c(o);fetch(o.href,t)}})();const p=document.querySelector("form"),a=document.querySelector(".images"),f=document.querySelector(".loader"),l=document.querySelector(".load-more"),y=w.create({method:"get",baseURL:"https://pixabay.com/api/",params:{key:"41610080-031e2cebad3f84a1c0bee486b",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}});let s=1;const E=()=>{s++};let d=new L(".images a",{captionsData:"alt",captionDelay:250}),m;p.addEventListener("submit",async e=>{e.preventDefault(),s=1,a.innerHTML="",f.style.display="block",m=e.target.elements.search.value;try{const r=await y({params:{q:m,page:s}});console.log(r.data.total),v(r.data)}catch{M()}f.style.display="none",p.reset()});l.addEventListener("click",async()=>{E();try{const e=await y({params:{q:m,page:s}});C(e.data),g()}catch{F(),g()}});const u=e=>e.hits.map(({largeImageURL:r,webformatURL:c,tags:i,likes:o,views:t,comments:n,downloads:b})=>`
    <li class="img">
       <a href="${r}"><img src="${c}" alt="${i}"></a>
      <ul class="img-info">
        <li class="img-info-item"><span>Likes</span> ${o}</li>
        <li class="img-info-item"><span>Views</span> ${t}</li>
        <li class="img-info-item"><span>Comments</span> ${n}</li>
        <li class="img-info-item"><span>Downloads</span> ${b}</li>
      </ul>
    </li>`).join(""),v=e=>{if(e.hits.length===0)throw new Error(e.status);a.innerHTML=u(e),l.style.display="block",Math.ceil(e.total/40)<=s&&F(),d.refresh()},C=e=>{if(Math.ceil(e.total/40)<=s)throw a.insertAdjacentHTML("beforeend",u(e)),d.refresh(),new Error(e.status);a.insertAdjacentHTML("beforeend",u(e)),d.refresh()},M=()=>{h.show({message:"Sorry, there are no images matching your search query. Please try again!",maxWidth:432,iconUrl:"./images/error-icon.svg",iconColor:"#FFFFFF",backgroundColor:"#EF4040",messageColor:"#FFFFFF",position:"topRight"}),l.style.display="none",a.innerHTML=""},F=()=>{h.show({message:"We're sorry, but you've reached the end of search results.",maxWidth:432,iconUrl:"./images/error-icon.svg",iconColor:"#FFFFFF",backgroundColor:"#87CEEB",messageColor:"#FFFFFF",position:"topRight"}),l.style.display="none"},g=()=>{const e=document.querySelector(".img").getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})};
//# sourceMappingURL=commonHelpers.js.map
